stages:
  - test

############################################################
######################## Variables #########################
############################################################


############################################################
######################## Tests #############################
############################################################
test_flake8:
  image: ejplatform/python:alpine
  stage: test
  script:
    - echo "Executando teste...."
