stages:
  - test
  - lint
  - build

############################################################
######################## Tests #############################
############################################################
test_backend:
  image: python:3
  stage: test
  script:
    - echo "Executando teste...."
    - pip install -r ./api/requirements.txt
    - pip install coverage
    - python ./api/manage.py test
    - coverage run --source='.' ./api/manage.py test
    - coverage report

test_front:
  image: node:12.4.0-alpine
  stage: test
  script:
    - echo "Executando teste...."
    - npm install -g @vue/cli && npm install -g @quasar/cli
    - quasar test --unit jest --dev="-m pwa"

lint_backend:
  image: python:3
  stage: lint
  script:
    - flake8 ./api/ --exclude=./api/task/,./api/api/settings.py

build_backend:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -f api/Dockerfile -t jppgomes .
    - docker login -u jppgomes -p trabalhofga
    - docker tag jppgomes jppgomes/jppgomes
    - docker push jppgomes/jppgomes

build_frontend:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -f client/Dockerfile -t clientbuild .
    - docker login -u jppgomes -p trabalhofga
    - docker tag jppgomes clientbuild/clientbuild
    - docker push jppgomes/clientbuild