stages:
  - test

############################################################
######################## Variables #########################
############################################################


############################################################
######################## Tests #############################
############################################################
test_backend:
  image: python:3
  stage: test
  script:
    - echo "Executando teste...."
    - pip install -r ./api/requirements.txt
    - python ./api/manage.py test

test_frontend:
  image: node:12.4.0-alpine
  stage: teste
  scrpit:
    - echo "Executando teste frontend"
    - npm install -g @vue/cli && npm install -g @quasar/cli
    - quasar test --unit jest --dev="-m pwa"
