stages:
  - test

############################################################
######################## Variables #########################
############################################################


############################################################
######################## Tests #############################
############################################################
test_flake8:
  image: python:3
  stage: test
  script:
    - echo "Executando teste...."
    - pip install -r ./api/requirements.txt
    - python ./api/manage.py test
