"""
Django apps for api project.

Generated by jp.
"""


from django.apps import AppConfig


class TaskConfig(AppConfig):
    """
    Django task for api project.

    Generated by jp.
    """

    default_auto_field = 'django.db.models.BigAutoField'
    name = 'task'
