name: TEst

on: push

jobs:
  health-check-job:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432 # exposing 5432 port for application to use
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2

      - name: Cache dependency # caching dependency will make our build faster.
        uses: actions/cache@v2 # for more info checkout pip section documentation at https://github.com/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.8 # setting python environment to 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # if you want multiple python version run just use matrix strategy in job config. See the documentation of GitHub Actions

      - name: Check Python version # checking the python version to see if 3.x is installed.
        run: python --version

      - name: Install requirements # install application requirements
        run: pip install -r api/requirements.txt

      - name: Install coverage
        run: pip install coverage

      - name: Install code style
        run: pip install pycodestyle

      - name: ⭐⭐ Run Test with django manage.py test # running tests
        run: python api/manage.py test
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres

      - name: ⭐⭐⭐⭐ Análise de cobertura de testes
        run: |
          coverage run api/manage.py test api
          coverage report --fail-under=90
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres