name: Test

on: push

jobs:
  Test_Job:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432 

    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2Test

      - name: Cache dependency # caching dependency will make our build faster.
        uses: actions/cache@v2 # for more info checkout pip section documentation at https://github.com/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.8 # setting python environment to 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Check Python version 
        run: python --version

      - name: Install requirements 
        run: pip install -r api/requirements.txt

      - name: Install coverage
        run: pip install coverage

      - name: Install code style
        run: pip install pycodestyle

      - name:  Run Test with django manage.py test # running tests
        run: python api/manage.py test
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres

      - name:  Análise de cobertura de testes
        run: |
          coverage run api/manage.py test api
          coverage report 
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost