name: 'coverage'
on: push

jobs:
  health-check-job:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432 
    


    steps:    
      - name: check python
        run:
          python -v

      - name: pwd
        run:
          pwd

      - name: cobertura de testes
        run: |          
          pip install coverage
          coverage run ../api/manage.py test api
          coverage report --fail-under=90
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
